# Generated by Django 5.1.4 on 2024-12-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="MarketRatesAggregated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentile_10_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("median_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentile_90_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("annual_volume", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
