# Generated by Django 5.1.4 on 2024-12-22 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketrates",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="marketratesaggregated",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="userrates",
            options={"managed": False},
        ),
    ]
