# Generated by Django 5.1.4 on 2024-12-22 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_marketrates_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="marketrates",
            table="market_rates",
        ),
        migrations.AlterModelTable(
            name="marketratesaggregated",
            table="market_rates_aggregated",
        ),
        migrations.AlterModelTable(
            name="userrates",
            table="user_rates",
        ),
    ]
